### ISSUE TITLE
[Request] Restart containers depending on unhealthy containers

### ISSUE THREAD

**Issue by Ansem93** [ericm/healscript#1]
Hi,
I'm really interested in this container. I would also suggest to add the possibility to restart containers depending on the unhealthy container.
This is my use case:
Basically I have a docker container used as netfwork from other containers. When I put on standby my computer and wake it up this container status will be "unhealthy" instead of "healthy", so I need to restart it and then all the other containers that will use it.

**Comment by ericm** [comment]
Hi,

You can do that since the docker socket is passed into the container. If
your network container goes down, have network.sh run `docker restart
network other_contianer`.

**Comment by Ansem93** [comment]
oh now I got it.
I thought that healscript already came with a script!
Instead I have to create the script right?

in my case should be
```
restart network_container
sleep 1m
restart depending_containers

```
and healscript will automatically restart when network_container will become unhealthy,. right?

**Comment by ericm** [comment]
Thats correct. As in the readme, the container is designed to run a custom script when another container becomes unhealthy
